// app/moviesData.ts
import type { Movie } from "./types/movie";

export const movies: Movie[] = [
  {
    id: 1,
    title: "Nobody - 2021",
    year: 2021,
    thumbnail: "/posters/nobody-poster.png",
    video: "/movies/Nobody.mp4",
    startTime: 120,
    category: "Action",
    subtitle: "/subtitles/Nobody2021.vtt",
    description:
      "A seemingly ordinary man reveals his hidden past when he takes on dangerous criminals after a home invasion.",
  },
  {
    id: 2,
    title: "Puss in Boots: The Last Wish",
    year: 2022,
    thumbnail: "/posters/PussNBoots.png",
    video: "/movies/PussNBoots.mp4",
    startTime: 120,
    category: "Animation",
    subtitle: "/subtitles/PussNBoots.vtt",
    description:
      "Puss in Boots embarks on a quest to restore his nine lives, facing magical foes and old friends along the way.",
  },
  {
    id: 3,
    title: "Train to Busan",
    year: 2016,
    thumbnail: "/posters/Train to busan.png",
    video: "/movies/Train to busan.mkv",
    startTime: 120,
    category: "Thriller",
    subtitle: "/subtitles/Train to busan.vtt",
    description:
      "A father and daughter fight for survival on a train as a zombie outbreak takes over South Korea.",
  },
  {
    id: 4,
    title: "Avengers: Endgame",
    year: 2019,
    thumbnail: "/posters/Avengers2019.png",
    video: "/movies/Avengers2019.mp4",
    startTime: 120,
    category: "Sci-Fi",
    subtitle: "/subtitles/Avengers2019.vtt",
    description:
      "The Avengers assemble once more to undo the devastation caused by Thanos and save the universe.",
  },
  {
    id: 5,
    title: "The Electric State",
    year: 2025,
    thumbnail: "/posters/ElectricState.png",
    video: "/movies/ElectricState.mkv",
    startTime: 120,
    category: "Action",
    subtitle: "/subtitles/ElectricState.vtt",
    description:
      "A teenage girl journeys through a retro-futuristic America with her robot companion to find her brother.",
  },
  {
    id: 6,
    title: "The Conjuring",
    year: 2013,
    thumbnail: "/posters/The Conjuring.png",
    video: "/movies/The Conjuring.mp4",
    startTime: 120,
    category: "Horror",
    subtitle: "/subtitles/The Conjuring.vtt",
    description:
      "Paranormal investigators Ed and Lorraine Warren confront a dark presence haunting a family farmhouse.",
  },
  {
    id: 7,
    title: "Avengers: Infinity War",
    year: 2018,
    thumbnail: "/posters/Avengers2018.png",
    video: "/movies/Avengers2018.mp4",
    startTime: 120,
    category: "Sci-Fi",
    subtitle: "/subtitles/Avengers2018.vtt",
    description:
      "The Avengers and their allies face their greatest threat yet — Thanos — in a battle to save existence itself.",
  },
  {
    id: 8,
    title: "How to Train Your Dragon: The Hidden World",
    year: 2019,
    thumbnail: "/posters/How to train your dragon - hidden.png",
    video: "/movies/How to train your dragon - hidden.mp4",
    startTime: 120,
    category: "Animation",
    subtitle: "/subtitles/How to train your dragon - hidden.vtt",
    description:
      "Hiccup and Toothless embark on a journey to discover the hidden world before a tyrant hunts down dragons.",
  },
  {
    id: 9,
    title: "Papillon",
    year: 2017,
    thumbnail: "/posters/Papillon.png",
    video: "/movies/Papillon.mp4",
    startTime: 120,
    category: "True Crime",
    subtitle: "/subtitles/Papillon.vtt",
    description:
      "The story of Henri 'Papillon' Charrière's imprisonment and daring escape from a notorious penal colony.",
  },
  {
    id: 10,
    title: "Transformers: Rise of the Beasts",
    year: 2023,
    thumbnail: "/posters/Transformers.png",
    video: "/movies/Transformers.mp4",
    startTime: 120,
    category: "Sci-Fi",
    subtitle: "/subtitles/Transformers.vtt",
    description:
      "The Autobots join forces with the Maximals to protect Earth from a new enemy that threatens the universe.",
  },
  {
    id: 11,
    title: "The Old Guard 2",
    year: 2025,
    thumbnail: "/posters/The old guard 2.png",
    video: "/movies/The old guard 2.mkv",
    startTime: 120,
    category: "Action",
    subtitle: "/subtitles/The old guard 2.vtt",
    description:
      "Andy leads immortal warriors against a powerful enemy threatening their group. They grapple with the resurfacing of a long-lost immortal, complicating their mission to safeguard humanity.",
  },
  {
    id: 12,
    title: "Elemental",
    year: 2023,
    thumbnail: "/posters/Elemental.png",
    video: "/movies/Elemental.mp4",
    startTime: 120,
    category: "Animation",
    subtitle: "/subtitles/Elemental.vtt",
    description:
      "Follows Ember and Wade, in a city where fire-, water-, earth- and air-residents live together.",
  },
  {
    id: 13,
    title: "Ballerina 2025",
    year: 2025,
    thumbnail: "/posters/Ballerina.png",
    video: "/movies/Ballerina 2025.mkv",
    startTime: 120,
    category: "Action",
    subtitle: "/subtitles/Ballerina.vtt",
    description:
      "An assassin trained in the traditions of the Ruska Roma organization sets out to seek revenge after her father's death.",
  },
  {
    id: 14,
    title: "Sonic the Hedgehog 3",
    year: 2024,
    thumbnail: "/posters/Sonic the hedgehog 3.png",
    video: "/movies/Sonic the hedgehog 3.mkv",
    startTime: 120,
    category: "Fantasy",
    subtitle: "/subtitles/Sonic the hedgehog 3.vtt",
    description:
      "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched, Team Sonic must seek out an unlikely alliance.",
  },
  {
    id: 15,
    title: "Sonic the Hedgehog 2",
    year: 2022,
    thumbnail: "/posters/Sonic the hedgehog 2.png",
    video: "/movies/Sonic the hedgehog 2.mp4",
    startTime: 120,
    category: "Fantasy",
    subtitle: "/subtitles/Sonic the hedgehog 2.vtt",
    description:
      "When Dr. Robotnik returns with a new partner, Knuckles, in search of an emerald that has the power to destroy civilizations, Sonic teams up with his own sidekick, Tails, on a journey across the world to find the emerald first.",
  },
  {
    id: 16,
    title: "Until Dawn",
    year: 2025,
    thumbnail: "/posters/Until dawn.png",
    video: "/movies/Until Dawn 2025.mkv",
    startTime: 120,
    category: "Horror",
    subtitle: "/subtitles/Until Dawn.vtt",
    description:
      "A group of friends trapped in a time loop, where mysterious foes chase and kill them in gruesome ways, must survive until dawn to escape it.",
  },
  {
    id: 17,
    title: "Evil Dead Rise",
    year: 2023,
    thumbnail: "/posters/Evil dead rise.png",
    video: "/movies/Evil Dead Rise 2023.mp4",
    startTime: 120,
    category: "Horror",
    subtitle: "/subtitles/Evil dead rise 2023.vtt",
    description:
      "A twisted tale of two estranged sisters whose reunion is cut short by the rise of flesh-possessing demons, thrusting them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
  },
  {
    id: 18,
    title: "Saw X",
    year: 2023,
    thumbnail: "/posters/Saw X.png",
    video: "/movies/Saw X.mkv",
    startTime: 120,
    category: "Thriller",
    subtitle: "/subtitles/Saw X.vtt",
    description:
      "A twisted tale of two estranged sisters whose reunion is cut short by the rise of flesh-possessing demons, thrusting them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
  },
  {
    id: 19,
    title: "Pirates of the Caribbean: Dead Men Tell No Tales",
    year: 2017,
    thumbnail: "/posters/Pirates of the caribbean dead men tell no tales.png",
    video: "/movies/Pirates of the Caribbean - Dead Men Tell No tales.mp4",
    startTime: 120,
    category: "Fantasy",
    subtitle: "/subtitles/Pirates of the caribbean dead men tell no tales.vtt",
    description:
      "Blacksmith Will Turner teams up with eccentric pirate Captain Jack Sparrow to save Elizabeth Swann, the governor's daughter and his love, from Jack's former pirate allies, who are now undead.",
  },
  {
    id: 20,
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    year: 2003,
    thumbnail: "/posters/Pirates of the caribbean curse of the black pearl.png",
    video: "/movies/Pirates of the Caribbean The Curse of the Black Pearl.mp4",
    startTime: 120,
    category: "Fantasy",
    subtitle:
      "/subtitles/Pirates of the Caribbean The Curse of the Black Pearl.vtt",
    description:
      "Blacksmith Will Turner teams up with eccentric pirate Captain Jack Sparrow to save Elizabeth Swann, the governor's daughter and his love, from Jack's former pirate allies, who are now undead.",
  },
  {
    id: 22,
    title: "Pirates of the Caribbean: At World's End",
    year: 2007,
    thumbnail: "/posters/Pirates of the Caribbean At World's End.png",
    video: "/movies/Pirates of the Caribbean At World's End (2007).mp4",
    startTime: 120,
    category: "Fantasy",
    subtitle: "/subtitles/Pirates of the Caribbean At World's End.vtt",
    description:
      "Will Turner, Elizabeth Swann, Hector Barbossa, and the crew of the Black Pearl try and rescue Jack from davy jones locker and prepare to fight Lord Cutler Beckett, who controls Davy Jones and the Flying Dutchman.",
  },
  {
    id: 23,
    title: "Pirates of the Caribbean Dead Man's Chest",
    year: 2006,
    thumbnail: "/posters/Pirates of the Caribbean Dead Man's Chest.png",
    video: "/movies/Pirates of the Caribbean Dead Man's Chest.mp4",
    startTime: 120,
    category: "Fantasy",
    subtitle: "/subtitles/Pirates of the Caribbean Dead Man's Chest.vtt",
    description:
      "Jack Sparrow races to recover the heart of Davy Jones to avoid enslaving his soul to Jones' service, as other friends and foes seek the heart for their own agenda as well.",
  },
  {
    id: 24,
    title: "Nowhere",
    year: 2023,
    thumbnail: "/posters/nowhere.png",
    video: "/movies/Nowhere.mp4",
    startTime: 120,
    category: "Thriller",
    subtitle: "/subtitles/nowhere.vtt",
    description:
      "A young pregnant woman named Mia escapes from a country at war by hiding in a maritime container aboard a cargo ship. After a violent storm, Mia gives birth to her child while lost at sea, where she must fight to survive.",
  },
  {
    id: 25,
    title: "Anabelle",
    year: 2014,
    thumbnail: "/posters/anabelle.png",
    video: "/movies/Anabelle.mp4",
    startTime: 120,
    category: "Horror",
    subtitle: "/subtitles/",
    description:
      "A couple begins to experience terrifying supernatural occurrences involving a vintage doll shortly after their home is invaded by satanic cultists.",
  },
  {
    id: 26,
    title: "The Bad Guys 2",
    year: 2025,
    thumbnail: "/posters/the bad guy 2.png",
    video: "/movies/The Bad Guys 2.mkv",
    startTime: 120,
    category: "Animation",
    subtitle: "/subtitles/the bad guy 2.vtt",
    description:
      "The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.",
  },
  {
    id: 27,
    title: "Dune: Part Two",
    year: 2024,
    thumbnail: "/posters/dune part two.png",
    video: "/movies/Dune Part Two.mp4",
    startTime: 120,
    category: "Action",
    subtitle: "/subtitles/",
    description:
      "Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future.",
  },
  {
    id: 28,
    title: "Nobody 2",
    year: 2025,
    thumbnail: "/posters/nobody2.png",
    video: "/movies/Nobody 2.mp4",
    startTime: 120,
    category: "Action",
    subtitle: "/subtitles/nobody2.vtt",
    description:
      "Suburban dad Hutch Mansell, a former lethal assassin, is pulled back into his violent past after thwarting a home invasion, setting off a chain of events that unravels secrets about his wife Becca's past and his own.",
  },
  {
    id: 30,
    title: "F1: The Movie",
    year: 2025,
    thumbnail: "/posters/f1 the movie.png",
    video: "/movies/F1 The Movie.mkv",
    startTime: 120,
    category: "Action",
    subtitle: "/subtitles/f1 the movie.vtt",
    description:
      "A Formula One driver comes out of retirement to mentor and team up with a younger driver.",
  },
];
